server:
  port: 8090 #以配置中心为准（现在此端口不起作用）


spring:
  profiles:
    active: service
  #数据源配置
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    # 使用druid数据源连接池
    type:  com.alibaba.druid.pool.DruidDataSource
    #加载驱动
    driverClassName: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  # bean覆盖
  main:
    allow-bean-definition-overriding: true

  application:
    # 指定注册到eureka server上的服务名称
    name: ${mjx.application.name}

  # thymeleaf 配置
  thymeleaf:
    prefix: classpath:/thymeleaf/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    # 开发时关闭缓存,不然没法看到实时页面
    cache: false
  mvc:
    # static 文件夹下的静态文件访问路径
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/

  #配置mybatis
  mybatis:
    mapperLocations: classpath*:mapper/*.xml
    typeAliasesPackage: com.vedeng.mjx.domain
    configLocation: classpath*:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: ${eureka.client.service-url}
    fetchRegistry: true
    # 服务清单的缓存更新时间，默认30秒一次
    registry-fetch-interval-seconds: ${eureka.fetch_interval_seconds}
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    preferIpAddress: true
    lease-renewal-interval-in-seconds: ${renewal_interval_in_seconds}
    lease-expiration-duration-in-seconds: ${expiration_duration_in_seconds}

shiro:
  loginUrl: /login.html#/login

  # Let Shiro Manage the sessions
  userNativeSessionManager: true

  # disable URL session rewriting
  sessionManager:
    sessionIdUrlRewritingEnabled: false

ribbon:
  ReadTimeout: ${feign.read_timeout}
  ConnectTimeout: ${feign.connect_timeout}
  eureka:
    enabled: true   #important

logging:
  config: classpath:logback-spring.xml

mybatis:
  # spring boot集成mybatis的方式打印sql test
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

xxlyml:
  job:
    admin:
      addresses: ${xxl.job.admin.addresses}
    executor:
      appname: ${xxl.job.executor.appname}
      ip:
      port: ${xxl.job.executor.port}
      logpath: ${xxl.job.executor.logpath}
      logretentiondays: ${xxl.job.executor.logretentiondays}
    accessToken: ${xxl.job.accessToken}

goodsName: goods
passportApiName: PASSPORT-API