package com.vedeng.mjx.domain;

public class TOpSkuKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.SKU_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Long skuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.SKU_ID
     *
     * @return the value of T_OP_SKU.SKU_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.SKU_ID
     *
     * @param skuId the value for T_OP_SKU.SKU_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }
}