package com.vedeng.mjx.domain;

import java.util.Date;

public class TOpSku extends TOpSkuKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.SKU_EXT_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Long skuExtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.SKU_NO
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private String skuNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.SKU_NAME
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private String skuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.SOURCE
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Boolean source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.PLATFROM_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Integer platfromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.BRAND_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.CATEGORY_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.CATEGORY_NAME_ERP
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private String categoryNameErp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.STATUS
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.IS_NEW
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Byte isNew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.IS_HOT
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Byte isHot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.IS_SEVEN
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Byte isSeven;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.IS_ON_SALE
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Byte isOnSale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.IS_OP_SHOW
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Boolean isOpShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.OP_INSTITUTION
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private String opInstitution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.OP_SALESPOINT
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private String opSalespoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.CREATOR
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.CREATE_TIME
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.UPDATER
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Integer updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.UPDATE_TIME
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.IS_DEL
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private Byte isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.SKU_EXT_ID
     *
     * @return the value of T_OP_SKU.SKU_EXT_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Long getSkuExtId() {
        return skuExtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.SKU_EXT_ID
     *
     * @param skuExtId the value for T_OP_SKU.SKU_EXT_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setSkuExtId(Long skuExtId) {
        this.skuExtId = skuExtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.SKU_NO
     *
     * @return the value of T_OP_SKU.SKU_NO
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public String getSkuNo() {
        return skuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.SKU_NO
     *
     * @param skuNo the value for T_OP_SKU.SKU_NO
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setSkuNo(String skuNo) {
        this.skuNo = skuNo == null ? null : skuNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.SKU_NAME
     *
     * @return the value of T_OP_SKU.SKU_NAME
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.SKU_NAME
     *
     * @param skuName the value for T_OP_SKU.SKU_NAME
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.SOURCE
     *
     * @return the value of T_OP_SKU.SOURCE
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Boolean getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.SOURCE
     *
     * @param source the value for T_OP_SKU.SOURCE
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setSource(Boolean source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.PLATFROM_ID
     *
     * @return the value of T_OP_SKU.PLATFROM_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Integer getPlatfromId() {
        return platfromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.PLATFROM_ID
     *
     * @param platfromId the value for T_OP_SKU.PLATFROM_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setPlatfromId(Integer platfromId) {
        this.platfromId = platfromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.BRAND_ID
     *
     * @return the value of T_OP_SKU.BRAND_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.BRAND_ID
     *
     * @param brandId the value for T_OP_SKU.BRAND_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.CATEGORY_ID
     *
     * @return the value of T_OP_SKU.CATEGORY_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.CATEGORY_ID
     *
     * @param categoryId the value for T_OP_SKU.CATEGORY_ID
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.CATEGORY_NAME_ERP
     *
     * @return the value of T_OP_SKU.CATEGORY_NAME_ERP
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public String getCategoryNameErp() {
        return categoryNameErp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.CATEGORY_NAME_ERP
     *
     * @param categoryNameErp the value for T_OP_SKU.CATEGORY_NAME_ERP
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setCategoryNameErp(String categoryNameErp) {
        this.categoryNameErp = categoryNameErp == null ? null : categoryNameErp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.STATUS
     *
     * @return the value of T_OP_SKU.STATUS
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.STATUS
     *
     * @param status the value for T_OP_SKU.STATUS
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.IS_NEW
     *
     * @return the value of T_OP_SKU.IS_NEW
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Byte getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.IS_NEW
     *
     * @param isNew the value for T_OP_SKU.IS_NEW
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setIsNew(Byte isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.IS_HOT
     *
     * @return the value of T_OP_SKU.IS_HOT
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Byte getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.IS_HOT
     *
     * @param isHot the value for T_OP_SKU.IS_HOT
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setIsHot(Byte isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.IS_SEVEN
     *
     * @return the value of T_OP_SKU.IS_SEVEN
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Byte getIsSeven() {
        return isSeven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.IS_SEVEN
     *
     * @param isSeven the value for T_OP_SKU.IS_SEVEN
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setIsSeven(Byte isSeven) {
        this.isSeven = isSeven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.IS_ON_SALE
     *
     * @return the value of T_OP_SKU.IS_ON_SALE
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Byte getIsOnSale() {
        return isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.IS_ON_SALE
     *
     * @param isOnSale the value for T_OP_SKU.IS_ON_SALE
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setIsOnSale(Byte isOnSale) {
        this.isOnSale = isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.IS_OP_SHOW
     *
     * @return the value of T_OP_SKU.IS_OP_SHOW
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Boolean getIsOpShow() {
        return isOpShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.IS_OP_SHOW
     *
     * @param isOpShow the value for T_OP_SKU.IS_OP_SHOW
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setIsOpShow(Boolean isOpShow) {
        this.isOpShow = isOpShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.OP_INSTITUTION
     *
     * @return the value of T_OP_SKU.OP_INSTITUTION
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public String getOpInstitution() {
        return opInstitution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.OP_INSTITUTION
     *
     * @param opInstitution the value for T_OP_SKU.OP_INSTITUTION
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setOpInstitution(String opInstitution) {
        this.opInstitution = opInstitution == null ? null : opInstitution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.OP_SALESPOINT
     *
     * @return the value of T_OP_SKU.OP_SALESPOINT
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public String getOpSalespoint() {
        return opSalespoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.OP_SALESPOINT
     *
     * @param opSalespoint the value for T_OP_SKU.OP_SALESPOINT
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setOpSalespoint(String opSalespoint) {
        this.opSalespoint = opSalespoint == null ? null : opSalespoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.CREATOR
     *
     * @return the value of T_OP_SKU.CREATOR
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.CREATOR
     *
     * @param creator the value for T_OP_SKU.CREATOR
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.CREATE_TIME
     *
     * @return the value of T_OP_SKU.CREATE_TIME
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.CREATE_TIME
     *
     * @param createTime the value for T_OP_SKU.CREATE_TIME
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.UPDATER
     *
     * @return the value of T_OP_SKU.UPDATER
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Integer getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.UPDATER
     *
     * @param updater the value for T_OP_SKU.UPDATER
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.UPDATE_TIME
     *
     * @return the value of T_OP_SKU.UPDATE_TIME
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.UPDATE_TIME
     *
     * @param updateTime the value for T_OP_SKU.UPDATE_TIME
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.IS_DEL
     *
     * @return the value of T_OP_SKU.IS_DEL
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.IS_DEL
     *
     * @param isDel the value for T_OP_SKU.IS_DEL
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }
}