package com.vedeng.mjx.domain;

public class TOpSkuWithBLOBs extends TOpSku {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.SKU_TITLE
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private String skuTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.OP_COMPETE
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private String opCompete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OP_SKU.OP_GOODSDATA
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    private String opGoodsdata;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.SKU_TITLE
     *
     * @return the value of T_OP_SKU.SKU_TITLE
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public String getSkuTitle() {
        return skuTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.SKU_TITLE
     *
     * @param skuTitle the value for T_OP_SKU.SKU_TITLE
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setSkuTitle(String skuTitle) {
        this.skuTitle = skuTitle == null ? null : skuTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.OP_COMPETE
     *
     * @return the value of T_OP_SKU.OP_COMPETE
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public String getOpCompete() {
        return opCompete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.OP_COMPETE
     *
     * @param opCompete the value for T_OP_SKU.OP_COMPETE
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setOpCompete(String opCompete) {
        this.opCompete = opCompete == null ? null : opCompete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OP_SKU.OP_GOODSDATA
     *
     * @return the value of T_OP_SKU.OP_GOODSDATA
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public String getOpGoodsdata() {
        return opGoodsdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OP_SKU.OP_GOODSDATA
     *
     * @param opGoodsdata the value for T_OP_SKU.OP_GOODSDATA
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    public void setOpGoodsdata(String opGoodsdata) {
        this.opGoodsdata = opGoodsdata == null ? null : opGoodsdata.trim();
    }
}