package com.vedeng.mjx.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VOrderGoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    public VOrderGoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderGoodsIdIsNull() {
            addCriterion("ORDER_GOODS_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdIsNotNull() {
            addCriterion("ORDER_GOODS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdEqualTo(Integer value) {
            addCriterion("ORDER_GOODS_ID =", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdNotEqualTo(Integer value) {
            addCriterion("ORDER_GOODS_ID <>", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdGreaterThan(Integer value) {
            addCriterion("ORDER_GOODS_ID >", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDER_GOODS_ID >=", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdLessThan(Integer value) {
            addCriterion("ORDER_GOODS_ID <", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdLessThanOrEqualTo(Integer value) {
            addCriterion("ORDER_GOODS_ID <=", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdIn(List<Integer> values) {
            addCriterion("ORDER_GOODS_ID in", values, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdNotIn(List<Integer> values) {
            addCriterion("ORDER_GOODS_ID not in", values, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_GOODS_ID between", value1, value2, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_GOODS_ID not between", value1, value2, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("ORDER_NO =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("ORDER_NO <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("ORDER_NO >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NO >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("ORDER_NO <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NO <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("ORDER_NO like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("ORDER_NO not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("ORDER_NO in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("ORDER_NO not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("ORDER_NO between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("ORDER_NO not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("GOODS_ID is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("GOODS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(Integer value) {
            addCriterion("GOODS_ID =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(Integer value) {
            addCriterion("GOODS_ID <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(Integer value) {
            addCriterion("GOODS_ID >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("GOODS_ID >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(Integer value) {
            addCriterion("GOODS_ID <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(Integer value) {
            addCriterion("GOODS_ID <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<Integer> values) {
            addCriterion("GOODS_ID in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<Integer> values) {
            addCriterion("GOODS_ID not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(Integer value1, Integer value2) {
            addCriterion("GOODS_ID between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("GOODS_ID not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsNumIsNull() {
            addCriterion("GOODS_NUM is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNumIsNotNull() {
            addCriterion("GOODS_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNumEqualTo(Integer value) {
            addCriterion("GOODS_NUM =", value, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumNotEqualTo(Integer value) {
            addCriterion("GOODS_NUM <>", value, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumGreaterThan(Integer value) {
            addCriterion("GOODS_NUM >", value, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("GOODS_NUM >=", value, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumLessThan(Integer value) {
            addCriterion("GOODS_NUM <", value, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumLessThanOrEqualTo(Integer value) {
            addCriterion("GOODS_NUM <=", value, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumIn(List<Integer> values) {
            addCriterion("GOODS_NUM in", values, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumNotIn(List<Integer> values) {
            addCriterion("GOODS_NUM not in", values, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumBetween(Integer value1, Integer value2) {
            addCriterion("GOODS_NUM between", value1, value2, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumNotBetween(Integer value1, Integer value2) {
            addCriterion("GOODS_NUM not between", value1, value2, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIsNull() {
            addCriterion("GOODS_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIsNotNull() {
            addCriterion("GOODS_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceEqualTo(BigDecimal value) {
            addCriterion("GOODS_PRICE =", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotEqualTo(BigDecimal value) {
            addCriterion("GOODS_PRICE <>", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceGreaterThan(BigDecimal value) {
            addCriterion("GOODS_PRICE >", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("GOODS_PRICE >=", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceLessThan(BigDecimal value) {
            addCriterion("GOODS_PRICE <", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("GOODS_PRICE <=", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIn(List<BigDecimal> values) {
            addCriterion("GOODS_PRICE in", values, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotIn(List<BigDecimal> values) {
            addCriterion("GOODS_PRICE not in", values, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GOODS_PRICE between", value1, value2, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GOODS_PRICE not between", value1, value2, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andMarketMomeyIsNull() {
            addCriterion("MARKET_MOMEY is null");
            return (Criteria) this;
        }

        public Criteria andMarketMomeyIsNotNull() {
            addCriterion("MARKET_MOMEY is not null");
            return (Criteria) this;
        }

        public Criteria andMarketMomeyEqualTo(BigDecimal value) {
            addCriterion("MARKET_MOMEY =", value, "marketMomey");
            return (Criteria) this;
        }

        public Criteria andMarketMomeyNotEqualTo(BigDecimal value) {
            addCriterion("MARKET_MOMEY <>", value, "marketMomey");
            return (Criteria) this;
        }

        public Criteria andMarketMomeyGreaterThan(BigDecimal value) {
            addCriterion("MARKET_MOMEY >", value, "marketMomey");
            return (Criteria) this;
        }

        public Criteria andMarketMomeyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MARKET_MOMEY >=", value, "marketMomey");
            return (Criteria) this;
        }

        public Criteria andMarketMomeyLessThan(BigDecimal value) {
            addCriterion("MARKET_MOMEY <", value, "marketMomey");
            return (Criteria) this;
        }

        public Criteria andMarketMomeyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MARKET_MOMEY <=", value, "marketMomey");
            return (Criteria) this;
        }

        public Criteria andMarketMomeyIn(List<BigDecimal> values) {
            addCriterion("MARKET_MOMEY in", values, "marketMomey");
            return (Criteria) this;
        }

        public Criteria andMarketMomeyNotIn(List<BigDecimal> values) {
            addCriterion("MARKET_MOMEY not in", values, "marketMomey");
            return (Criteria) this;
        }

        public Criteria andMarketMomeyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MARKET_MOMEY between", value1, value2, "marketMomey");
            return (Criteria) this;
        }

        public Criteria andMarketMomeyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MARKET_MOMEY not between", value1, value2, "marketMomey");
            return (Criteria) this;
        }

        public Criteria andSalesMoneyIsNull() {
            addCriterion("SALES_MONEY is null");
            return (Criteria) this;
        }

        public Criteria andSalesMoneyIsNotNull() {
            addCriterion("SALES_MONEY is not null");
            return (Criteria) this;
        }

        public Criteria andSalesMoneyEqualTo(BigDecimal value) {
            addCriterion("SALES_MONEY =", value, "salesMoney");
            return (Criteria) this;
        }

        public Criteria andSalesMoneyNotEqualTo(BigDecimal value) {
            addCriterion("SALES_MONEY <>", value, "salesMoney");
            return (Criteria) this;
        }

        public Criteria andSalesMoneyGreaterThan(BigDecimal value) {
            addCriterion("SALES_MONEY >", value, "salesMoney");
            return (Criteria) this;
        }

        public Criteria andSalesMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SALES_MONEY >=", value, "salesMoney");
            return (Criteria) this;
        }

        public Criteria andSalesMoneyLessThan(BigDecimal value) {
            addCriterion("SALES_MONEY <", value, "salesMoney");
            return (Criteria) this;
        }

        public Criteria andSalesMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SALES_MONEY <=", value, "salesMoney");
            return (Criteria) this;
        }

        public Criteria andSalesMoneyIn(List<BigDecimal> values) {
            addCriterion("SALES_MONEY in", values, "salesMoney");
            return (Criteria) this;
        }

        public Criteria andSalesMoneyNotIn(List<BigDecimal> values) {
            addCriterion("SALES_MONEY not in", values, "salesMoney");
            return (Criteria) this;
        }

        public Criteria andSalesMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SALES_MONEY between", value1, value2, "salesMoney");
            return (Criteria) this;
        }

        public Criteria andSalesMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SALES_MONEY not between", value1, value2, "salesMoney");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNull() {
            addCriterion("GOODS_NAME is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNotNull() {
            addCriterion("GOODS_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameEqualTo(String value) {
            addCriterion("GOODS_NAME =", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotEqualTo(String value) {
            addCriterion("GOODS_NAME <>", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThan(String value) {
            addCriterion("GOODS_NAME >", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("GOODS_NAME >=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThan(String value) {
            addCriterion("GOODS_NAME <", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("GOODS_NAME <=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLike(String value) {
            addCriterion("GOODS_NAME like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotLike(String value) {
            addCriterion("GOODS_NAME not like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIn(List<String> values) {
            addCriterion("GOODS_NAME in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotIn(List<String> values) {
            addCriterion("GOODS_NAME not in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameBetween(String value1, String value2) {
            addCriterion("GOODS_NAME between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotBetween(String value1, String value2) {
            addCriterion("GOODS_NAME not between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsSkuIsNull() {
            addCriterion("GOODS_SKU is null");
            return (Criteria) this;
        }

        public Criteria andGoodsSkuIsNotNull() {
            addCriterion("GOODS_SKU is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsSkuEqualTo(String value) {
            addCriterion("GOODS_SKU =", value, "goodsSku");
            return (Criteria) this;
        }

        public Criteria andGoodsSkuNotEqualTo(String value) {
            addCriterion("GOODS_SKU <>", value, "goodsSku");
            return (Criteria) this;
        }

        public Criteria andGoodsSkuGreaterThan(String value) {
            addCriterion("GOODS_SKU >", value, "goodsSku");
            return (Criteria) this;
        }

        public Criteria andGoodsSkuGreaterThanOrEqualTo(String value) {
            addCriterion("GOODS_SKU >=", value, "goodsSku");
            return (Criteria) this;
        }

        public Criteria andGoodsSkuLessThan(String value) {
            addCriterion("GOODS_SKU <", value, "goodsSku");
            return (Criteria) this;
        }

        public Criteria andGoodsSkuLessThanOrEqualTo(String value) {
            addCriterion("GOODS_SKU <=", value, "goodsSku");
            return (Criteria) this;
        }

        public Criteria andGoodsSkuLike(String value) {
            addCriterion("GOODS_SKU like", value, "goodsSku");
            return (Criteria) this;
        }

        public Criteria andGoodsSkuNotLike(String value) {
            addCriterion("GOODS_SKU not like", value, "goodsSku");
            return (Criteria) this;
        }

        public Criteria andGoodsSkuIn(List<String> values) {
            addCriterion("GOODS_SKU in", values, "goodsSku");
            return (Criteria) this;
        }

        public Criteria andGoodsSkuNotIn(List<String> values) {
            addCriterion("GOODS_SKU not in", values, "goodsSku");
            return (Criteria) this;
        }

        public Criteria andGoodsSkuBetween(String value1, String value2) {
            addCriterion("GOODS_SKU between", value1, value2, "goodsSku");
            return (Criteria) this;
        }

        public Criteria andGoodsSkuNotBetween(String value1, String value2) {
            addCriterion("GOODS_SKU not between", value1, value2, "goodsSku");
            return (Criteria) this;
        }

        public Criteria andGoodsModelIsNull() {
            addCriterion("GOODS_MODEL is null");
            return (Criteria) this;
        }

        public Criteria andGoodsModelIsNotNull() {
            addCriterion("GOODS_MODEL is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsModelEqualTo(String value) {
            addCriterion("GOODS_MODEL =", value, "goodsModel");
            return (Criteria) this;
        }

        public Criteria andGoodsModelNotEqualTo(String value) {
            addCriterion("GOODS_MODEL <>", value, "goodsModel");
            return (Criteria) this;
        }

        public Criteria andGoodsModelGreaterThan(String value) {
            addCriterion("GOODS_MODEL >", value, "goodsModel");
            return (Criteria) this;
        }

        public Criteria andGoodsModelGreaterThanOrEqualTo(String value) {
            addCriterion("GOODS_MODEL >=", value, "goodsModel");
            return (Criteria) this;
        }

        public Criteria andGoodsModelLessThan(String value) {
            addCriterion("GOODS_MODEL <", value, "goodsModel");
            return (Criteria) this;
        }

        public Criteria andGoodsModelLessThanOrEqualTo(String value) {
            addCriterion("GOODS_MODEL <=", value, "goodsModel");
            return (Criteria) this;
        }

        public Criteria andGoodsModelLike(String value) {
            addCriterion("GOODS_MODEL like", value, "goodsModel");
            return (Criteria) this;
        }

        public Criteria andGoodsModelNotLike(String value) {
            addCriterion("GOODS_MODEL not like", value, "goodsModel");
            return (Criteria) this;
        }

        public Criteria andGoodsModelIn(List<String> values) {
            addCriterion("GOODS_MODEL in", values, "goodsModel");
            return (Criteria) this;
        }

        public Criteria andGoodsModelNotIn(List<String> values) {
            addCriterion("GOODS_MODEL not in", values, "goodsModel");
            return (Criteria) this;
        }

        public Criteria andGoodsModelBetween(String value1, String value2) {
            addCriterion("GOODS_MODEL between", value1, value2, "goodsModel");
            return (Criteria) this;
        }

        public Criteria andGoodsModelNotBetween(String value1, String value2) {
            addCriterion("GOODS_MODEL not between", value1, value2, "goodsModel");
            return (Criteria) this;
        }

        public Criteria andSpecsIsNull() {
            addCriterion("SPECS is null");
            return (Criteria) this;
        }

        public Criteria andSpecsIsNotNull() {
            addCriterion("SPECS is not null");
            return (Criteria) this;
        }

        public Criteria andSpecsEqualTo(String value) {
            addCriterion("SPECS =", value, "specs");
            return (Criteria) this;
        }

        public Criteria andSpecsNotEqualTo(String value) {
            addCriterion("SPECS <>", value, "specs");
            return (Criteria) this;
        }

        public Criteria andSpecsGreaterThan(String value) {
            addCriterion("SPECS >", value, "specs");
            return (Criteria) this;
        }

        public Criteria andSpecsGreaterThanOrEqualTo(String value) {
            addCriterion("SPECS >=", value, "specs");
            return (Criteria) this;
        }

        public Criteria andSpecsLessThan(String value) {
            addCriterion("SPECS <", value, "specs");
            return (Criteria) this;
        }

        public Criteria andSpecsLessThanOrEqualTo(String value) {
            addCriterion("SPECS <=", value, "specs");
            return (Criteria) this;
        }

        public Criteria andSpecsLike(String value) {
            addCriterion("SPECS like", value, "specs");
            return (Criteria) this;
        }

        public Criteria andSpecsNotLike(String value) {
            addCriterion("SPECS not like", value, "specs");
            return (Criteria) this;
        }

        public Criteria andSpecsIn(List<String> values) {
            addCriterion("SPECS in", values, "specs");
            return (Criteria) this;
        }

        public Criteria andSpecsNotIn(List<String> values) {
            addCriterion("SPECS not in", values, "specs");
            return (Criteria) this;
        }

        public Criteria andSpecsBetween(String value1, String value2) {
            addCriterion("SPECS between", value1, value2, "specs");
            return (Criteria) this;
        }

        public Criteria andSpecsNotBetween(String value1, String value2) {
            addCriterion("SPECS not between", value1, value2, "specs");
            return (Criteria) this;
        }

        public Criteria andStoreRemarkIsNull() {
            addCriterion("STORE_REMARK is null");
            return (Criteria) this;
        }

        public Criteria andStoreRemarkIsNotNull() {
            addCriterion("STORE_REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andStoreRemarkEqualTo(String value) {
            addCriterion("STORE_REMARK =", value, "storeRemark");
            return (Criteria) this;
        }

        public Criteria andStoreRemarkNotEqualTo(String value) {
            addCriterion("STORE_REMARK <>", value, "storeRemark");
            return (Criteria) this;
        }

        public Criteria andStoreRemarkGreaterThan(String value) {
            addCriterion("STORE_REMARK >", value, "storeRemark");
            return (Criteria) this;
        }

        public Criteria andStoreRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_REMARK >=", value, "storeRemark");
            return (Criteria) this;
        }

        public Criteria andStoreRemarkLessThan(String value) {
            addCriterion("STORE_REMARK <", value, "storeRemark");
            return (Criteria) this;
        }

        public Criteria andStoreRemarkLessThanOrEqualTo(String value) {
            addCriterion("STORE_REMARK <=", value, "storeRemark");
            return (Criteria) this;
        }

        public Criteria andStoreRemarkLike(String value) {
            addCriterion("STORE_REMARK like", value, "storeRemark");
            return (Criteria) this;
        }

        public Criteria andStoreRemarkNotLike(String value) {
            addCriterion("STORE_REMARK not like", value, "storeRemark");
            return (Criteria) this;
        }

        public Criteria andStoreRemarkIn(List<String> values) {
            addCriterion("STORE_REMARK in", values, "storeRemark");
            return (Criteria) this;
        }

        public Criteria andStoreRemarkNotIn(List<String> values) {
            addCriterion("STORE_REMARK not in", values, "storeRemark");
            return (Criteria) this;
        }

        public Criteria andStoreRemarkBetween(String value1, String value2) {
            addCriterion("STORE_REMARK between", value1, value2, "storeRemark");
            return (Criteria) this;
        }

        public Criteria andStoreRemarkNotBetween(String value1, String value2) {
            addCriterion("STORE_REMARK not between", value1, value2, "storeRemark");
            return (Criteria) this;
        }

        public Criteria andSpuIdIsNull() {
            addCriterion("SPU_ID is null");
            return (Criteria) this;
        }

        public Criteria andSpuIdIsNotNull() {
            addCriterion("SPU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSpuIdEqualTo(Integer value) {
            addCriterion("SPU_ID =", value, "spuId");
            return (Criteria) this;
        }

        public Criteria andSpuIdNotEqualTo(Integer value) {
            addCriterion("SPU_ID <>", value, "spuId");
            return (Criteria) this;
        }

        public Criteria andSpuIdGreaterThan(Integer value) {
            addCriterion("SPU_ID >", value, "spuId");
            return (Criteria) this;
        }

        public Criteria andSpuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SPU_ID >=", value, "spuId");
            return (Criteria) this;
        }

        public Criteria andSpuIdLessThan(Integer value) {
            addCriterion("SPU_ID <", value, "spuId");
            return (Criteria) this;
        }

        public Criteria andSpuIdLessThanOrEqualTo(Integer value) {
            addCriterion("SPU_ID <=", value, "spuId");
            return (Criteria) this;
        }

        public Criteria andSpuIdIn(List<Integer> values) {
            addCriterion("SPU_ID in", values, "spuId");
            return (Criteria) this;
        }

        public Criteria andSpuIdNotIn(List<Integer> values) {
            addCriterion("SPU_ID not in", values, "spuId");
            return (Criteria) this;
        }

        public Criteria andSpuIdBetween(Integer value1, Integer value2) {
            addCriterion("SPU_ID between", value1, value2, "spuId");
            return (Criteria) this;
        }

        public Criteria andSpuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SPU_ID not between", value1, value2, "spuId");
            return (Criteria) this;
        }

        public Criteria andGoodsBrandNameIsNull() {
            addCriterion("GOODS_BRAND_NAME is null");
            return (Criteria) this;
        }

        public Criteria andGoodsBrandNameIsNotNull() {
            addCriterion("GOODS_BRAND_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsBrandNameEqualTo(String value) {
            addCriterion("GOODS_BRAND_NAME =", value, "goodsBrandName");
            return (Criteria) this;
        }

        public Criteria andGoodsBrandNameNotEqualTo(String value) {
            addCriterion("GOODS_BRAND_NAME <>", value, "goodsBrandName");
            return (Criteria) this;
        }

        public Criteria andGoodsBrandNameGreaterThan(String value) {
            addCriterion("GOODS_BRAND_NAME >", value, "goodsBrandName");
            return (Criteria) this;
        }

        public Criteria andGoodsBrandNameGreaterThanOrEqualTo(String value) {
            addCriterion("GOODS_BRAND_NAME >=", value, "goodsBrandName");
            return (Criteria) this;
        }

        public Criteria andGoodsBrandNameLessThan(String value) {
            addCriterion("GOODS_BRAND_NAME <", value, "goodsBrandName");
            return (Criteria) this;
        }

        public Criteria andGoodsBrandNameLessThanOrEqualTo(String value) {
            addCriterion("GOODS_BRAND_NAME <=", value, "goodsBrandName");
            return (Criteria) this;
        }

        public Criteria andGoodsBrandNameLike(String value) {
            addCriterion("GOODS_BRAND_NAME like", value, "goodsBrandName");
            return (Criteria) this;
        }

        public Criteria andGoodsBrandNameNotLike(String value) {
            addCriterion("GOODS_BRAND_NAME not like", value, "goodsBrandName");
            return (Criteria) this;
        }

        public Criteria andGoodsBrandNameIn(List<String> values) {
            addCriterion("GOODS_BRAND_NAME in", values, "goodsBrandName");
            return (Criteria) this;
        }

        public Criteria andGoodsBrandNameNotIn(List<String> values) {
            addCriterion("GOODS_BRAND_NAME not in", values, "goodsBrandName");
            return (Criteria) this;
        }

        public Criteria andGoodsBrandNameBetween(String value1, String value2) {
            addCriterion("GOODS_BRAND_NAME between", value1, value2, "goodsBrandName");
            return (Criteria) this;
        }

        public Criteria andGoodsBrandNameNotBetween(String value1, String value2) {
            addCriterion("GOODS_BRAND_NAME not between", value1, value2, "goodsBrandName");
            return (Criteria) this;
        }

        public Criteria andCouponAmountIsNull() {
            addCriterion("COUPON_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andCouponAmountIsNotNull() {
            addCriterion("COUPON_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andCouponAmountEqualTo(BigDecimal value) {
            addCriterion("COUPON_AMOUNT =", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountNotEqualTo(BigDecimal value) {
            addCriterion("COUPON_AMOUNT <>", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountGreaterThan(BigDecimal value) {
            addCriterion("COUPON_AMOUNT >", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COUPON_AMOUNT >=", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountLessThan(BigDecimal value) {
            addCriterion("COUPON_AMOUNT <", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("COUPON_AMOUNT <=", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountIn(List<BigDecimal> values) {
            addCriterion("COUPON_AMOUNT in", values, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountNotIn(List<BigDecimal> values) {
            addCriterion("COUPON_AMOUNT not in", values, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COUPON_AMOUNT between", value1, value2, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COUPON_AMOUNT not between", value1, value2, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andGoodsDomainIsNull() {
            addCriterion("GOODS_DOMAIN is null");
            return (Criteria) this;
        }

        public Criteria andGoodsDomainIsNotNull() {
            addCriterion("GOODS_DOMAIN is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsDomainEqualTo(String value) {
            addCriterion("GOODS_DOMAIN =", value, "goodsDomain");
            return (Criteria) this;
        }

        public Criteria andGoodsDomainNotEqualTo(String value) {
            addCriterion("GOODS_DOMAIN <>", value, "goodsDomain");
            return (Criteria) this;
        }

        public Criteria andGoodsDomainGreaterThan(String value) {
            addCriterion("GOODS_DOMAIN >", value, "goodsDomain");
            return (Criteria) this;
        }

        public Criteria andGoodsDomainGreaterThanOrEqualTo(String value) {
            addCriterion("GOODS_DOMAIN >=", value, "goodsDomain");
            return (Criteria) this;
        }

        public Criteria andGoodsDomainLessThan(String value) {
            addCriterion("GOODS_DOMAIN <", value, "goodsDomain");
            return (Criteria) this;
        }

        public Criteria andGoodsDomainLessThanOrEqualTo(String value) {
            addCriterion("GOODS_DOMAIN <=", value, "goodsDomain");
            return (Criteria) this;
        }

        public Criteria andGoodsDomainLike(String value) {
            addCriterion("GOODS_DOMAIN like", value, "goodsDomain");
            return (Criteria) this;
        }

        public Criteria andGoodsDomainNotLike(String value) {
            addCriterion("GOODS_DOMAIN not like", value, "goodsDomain");
            return (Criteria) this;
        }

        public Criteria andGoodsDomainIn(List<String> values) {
            addCriterion("GOODS_DOMAIN in", values, "goodsDomain");
            return (Criteria) this;
        }

        public Criteria andGoodsDomainNotIn(List<String> values) {
            addCriterion("GOODS_DOMAIN not in", values, "goodsDomain");
            return (Criteria) this;
        }

        public Criteria andGoodsDomainBetween(String value1, String value2) {
            addCriterion("GOODS_DOMAIN between", value1, value2, "goodsDomain");
            return (Criteria) this;
        }

        public Criteria andGoodsDomainNotBetween(String value1, String value2) {
            addCriterion("GOODS_DOMAIN not between", value1, value2, "goodsDomain");
            return (Criteria) this;
        }

        public Criteria andGoodsUriIsNull() {
            addCriterion("GOODS_URI is null");
            return (Criteria) this;
        }

        public Criteria andGoodsUriIsNotNull() {
            addCriterion("GOODS_URI is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsUriEqualTo(String value) {
            addCriterion("GOODS_URI =", value, "goodsUri");
            return (Criteria) this;
        }

        public Criteria andGoodsUriNotEqualTo(String value) {
            addCriterion("GOODS_URI <>", value, "goodsUri");
            return (Criteria) this;
        }

        public Criteria andGoodsUriGreaterThan(String value) {
            addCriterion("GOODS_URI >", value, "goodsUri");
            return (Criteria) this;
        }

        public Criteria andGoodsUriGreaterThanOrEqualTo(String value) {
            addCriterion("GOODS_URI >=", value, "goodsUri");
            return (Criteria) this;
        }

        public Criteria andGoodsUriLessThan(String value) {
            addCriterion("GOODS_URI <", value, "goodsUri");
            return (Criteria) this;
        }

        public Criteria andGoodsUriLessThanOrEqualTo(String value) {
            addCriterion("GOODS_URI <=", value, "goodsUri");
            return (Criteria) this;
        }

        public Criteria andGoodsUriLike(String value) {
            addCriterion("GOODS_URI like", value, "goodsUri");
            return (Criteria) this;
        }

        public Criteria andGoodsUriNotLike(String value) {
            addCriterion("GOODS_URI not like", value, "goodsUri");
            return (Criteria) this;
        }

        public Criteria andGoodsUriIn(List<String> values) {
            addCriterion("GOODS_URI in", values, "goodsUri");
            return (Criteria) this;
        }

        public Criteria andGoodsUriNotIn(List<String> values) {
            addCriterion("GOODS_URI not in", values, "goodsUri");
            return (Criteria) this;
        }

        public Criteria andGoodsUriBetween(String value1, String value2) {
            addCriterion("GOODS_URI between", value1, value2, "goodsUri");
            return (Criteria) this;
        }

        public Criteria andGoodsUriNotBetween(String value1, String value2) {
            addCriterion("GOODS_URI not between", value1, value2, "goodsUri");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumIsNull() {
            addCriterion("DELIVERY_NUM is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumIsNotNull() {
            addCriterion("DELIVERY_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumEqualTo(Integer value) {
            addCriterion("DELIVERY_NUM =", value, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumNotEqualTo(Integer value) {
            addCriterion("DELIVERY_NUM <>", value, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumGreaterThan(Integer value) {
            addCriterion("DELIVERY_NUM >", value, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("DELIVERY_NUM >=", value, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumLessThan(Integer value) {
            addCriterion("DELIVERY_NUM <", value, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumLessThanOrEqualTo(Integer value) {
            addCriterion("DELIVERY_NUM <=", value, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumIn(List<Integer> values) {
            addCriterion("DELIVERY_NUM in", values, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumNotIn(List<Integer> values) {
            addCriterion("DELIVERY_NUM not in", values, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumBetween(Integer value1, Integer value2) {
            addCriterion("DELIVERY_NUM between", value1, value2, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumNotBetween(Integer value1, Integer value2) {
            addCriterion("DELIVERY_NUM not between", value1, value2, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusIsNull() {
            addCriterion("DELIVERY_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusIsNotNull() {
            addCriterion("DELIVERY_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusEqualTo(Boolean value) {
            addCriterion("DELIVERY_STATUS =", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusNotEqualTo(Boolean value) {
            addCriterion("DELIVERY_STATUS <>", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusGreaterThan(Boolean value) {
            addCriterion("DELIVERY_STATUS >", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("DELIVERY_STATUS >=", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusLessThan(Boolean value) {
            addCriterion("DELIVERY_STATUS <", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("DELIVERY_STATUS <=", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusIn(List<Boolean> values) {
            addCriterion("DELIVERY_STATUS in", values, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusNotIn(List<Boolean> values) {
            addCriterion("DELIVERY_STATUS not in", values, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("DELIVERY_STATUS between", value1, value2, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("DELIVERY_STATUS not between", value1, value2, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIsNull() {
            addCriterion("DELIVERY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIsNotNull() {
            addCriterion("DELIVERY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeEqualTo(Date value) {
            addCriterion("DELIVERY_TIME =", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotEqualTo(Date value) {
            addCriterion("DELIVERY_TIME <>", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeGreaterThan(Date value) {
            addCriterion("DELIVERY_TIME >", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DELIVERY_TIME >=", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeLessThan(Date value) {
            addCriterion("DELIVERY_TIME <", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeLessThanOrEqualTo(Date value) {
            addCriterion("DELIVERY_TIME <=", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIn(List<Date> values) {
            addCriterion("DELIVERY_TIME in", values, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotIn(List<Date> values) {
            addCriterion("DELIVERY_TIME not in", values, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeBetween(Date value1, Date value2) {
            addCriterion("DELIVERY_TIME between", value1, value2, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotBetween(Date value1, Date value2) {
            addCriterion("DELIVERY_TIME not between", value1, value2, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andArrivalNumIsNull() {
            addCriterion("ARRIVAL_NUM is null");
            return (Criteria) this;
        }

        public Criteria andArrivalNumIsNotNull() {
            addCriterion("ARRIVAL_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalNumEqualTo(Integer value) {
            addCriterion("ARRIVAL_NUM =", value, "arrivalNum");
            return (Criteria) this;
        }

        public Criteria andArrivalNumNotEqualTo(Integer value) {
            addCriterion("ARRIVAL_NUM <>", value, "arrivalNum");
            return (Criteria) this;
        }

        public Criteria andArrivalNumGreaterThan(Integer value) {
            addCriterion("ARRIVAL_NUM >", value, "arrivalNum");
            return (Criteria) this;
        }

        public Criteria andArrivalNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("ARRIVAL_NUM >=", value, "arrivalNum");
            return (Criteria) this;
        }

        public Criteria andArrivalNumLessThan(Integer value) {
            addCriterion("ARRIVAL_NUM <", value, "arrivalNum");
            return (Criteria) this;
        }

        public Criteria andArrivalNumLessThanOrEqualTo(Integer value) {
            addCriterion("ARRIVAL_NUM <=", value, "arrivalNum");
            return (Criteria) this;
        }

        public Criteria andArrivalNumIn(List<Integer> values) {
            addCriterion("ARRIVAL_NUM in", values, "arrivalNum");
            return (Criteria) this;
        }

        public Criteria andArrivalNumNotIn(List<Integer> values) {
            addCriterion("ARRIVAL_NUM not in", values, "arrivalNum");
            return (Criteria) this;
        }

        public Criteria andArrivalNumBetween(Integer value1, Integer value2) {
            addCriterion("ARRIVAL_NUM between", value1, value2, "arrivalNum");
            return (Criteria) this;
        }

        public Criteria andArrivalNumNotBetween(Integer value1, Integer value2) {
            addCriterion("ARRIVAL_NUM not between", value1, value2, "arrivalNum");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusIsNull() {
            addCriterion("ARRIVAL_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusIsNotNull() {
            addCriterion("ARRIVAL_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusEqualTo(Boolean value) {
            addCriterion("ARRIVAL_STATUS =", value, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusNotEqualTo(Boolean value) {
            addCriterion("ARRIVAL_STATUS <>", value, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusGreaterThan(Boolean value) {
            addCriterion("ARRIVAL_STATUS >", value, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ARRIVAL_STATUS >=", value, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusLessThan(Boolean value) {
            addCriterion("ARRIVAL_STATUS <", value, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("ARRIVAL_STATUS <=", value, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusIn(List<Boolean> values) {
            addCriterion("ARRIVAL_STATUS in", values, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusNotIn(List<Boolean> values) {
            addCriterion("ARRIVAL_STATUS not in", values, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("ARRIVAL_STATUS between", value1, value2, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ARRIVAL_STATUS not between", value1, value2, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIsNull() {
            addCriterion("ARRIVAL_TIME is null");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIsNotNull() {
            addCriterion("ARRIVAL_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeEqualTo(Date value) {
            addCriterion("ARRIVAL_TIME =", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotEqualTo(Date value) {
            addCriterion("ARRIVAL_TIME <>", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeGreaterThan(Date value) {
            addCriterion("ARRIVAL_TIME >", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ARRIVAL_TIME >=", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeLessThan(Date value) {
            addCriterion("ARRIVAL_TIME <", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeLessThanOrEqualTo(Date value) {
            addCriterion("ARRIVAL_TIME <=", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIn(List<Date> values) {
            addCriterion("ARRIVAL_TIME in", values, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotIn(List<Date> values) {
            addCriterion("ARRIVAL_TIME not in", values, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeBetween(Date value1, Date value2) {
            addCriterion("ARRIVAL_TIME between", value1, value2, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotBetween(Date value1, Date value2) {
            addCriterion("ARRIVAL_TIME not between", value1, value2, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("IS_DEL is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("IS_DEL is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Boolean value) {
            addCriterion("IS_DEL =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Boolean value) {
            addCriterion("IS_DEL <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Boolean value) {
            addCriterion("IS_DEL >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_DEL >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Boolean value) {
            addCriterion("IS_DEL <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_DEL <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Boolean> values) {
            addCriterion("IS_DEL in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Boolean> values) {
            addCriterion("IS_DEL not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_DEL between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_DEL not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(Integer value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(Integer value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(Integer value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Integer value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(Integer value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Integer value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<Integer> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<Integer> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(Integer value1, Integer value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(Integer value1, Integer value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNull() {
            addCriterion("MOD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNotNull() {
            addCriterion("MOD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModTimeEqualTo(Date value) {
            addCriterion("MOD_TIME =", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotEqualTo(Date value) {
            addCriterion("MOD_TIME <>", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThan(Date value) {
            addCriterion("MOD_TIME >", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MOD_TIME >=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThan(Date value) {
            addCriterion("MOD_TIME <", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThanOrEqualTo(Date value) {
            addCriterion("MOD_TIME <=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeIn(List<Date> values) {
            addCriterion("MOD_TIME in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotIn(List<Date> values) {
            addCriterion("MOD_TIME not in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeBetween(Date value1, Date value2) {
            addCriterion("MOD_TIME between", value1, value2, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotBetween(Date value1, Date value2) {
            addCriterion("MOD_TIME not between", value1, value2, "modTime");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("UPDATER is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("UPDATER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(Integer value) {
            addCriterion("UPDATER =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(Integer value) {
            addCriterion("UPDATER <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(Integer value) {
            addCriterion("UPDATER >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(Integer value) {
            addCriterion("UPDATER >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(Integer value) {
            addCriterion("UPDATER <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(Integer value) {
            addCriterion("UPDATER <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<Integer> values) {
            addCriterion("UPDATER in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<Integer> values) {
            addCriterion("UPDATER not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(Integer value1, Integer value2) {
            addCriterion("UPDATER between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(Integer value1, Integer value2) {
            addCriterion("UPDATER not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andSkuAmountIsNull() {
            addCriterion("SKU_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andSkuAmountIsNotNull() {
            addCriterion("SKU_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andSkuAmountEqualTo(BigDecimal value) {
            addCriterion("SKU_AMOUNT =", value, "skuAmount");
            return (Criteria) this;
        }

        public Criteria andSkuAmountNotEqualTo(BigDecimal value) {
            addCriterion("SKU_AMOUNT <>", value, "skuAmount");
            return (Criteria) this;
        }

        public Criteria andSkuAmountGreaterThan(BigDecimal value) {
            addCriterion("SKU_AMOUNT >", value, "skuAmount");
            return (Criteria) this;
        }

        public Criteria andSkuAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SKU_AMOUNT >=", value, "skuAmount");
            return (Criteria) this;
        }

        public Criteria andSkuAmountLessThan(BigDecimal value) {
            addCriterion("SKU_AMOUNT <", value, "skuAmount");
            return (Criteria) this;
        }

        public Criteria andSkuAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SKU_AMOUNT <=", value, "skuAmount");
            return (Criteria) this;
        }

        public Criteria andSkuAmountIn(List<BigDecimal> values) {
            addCriterion("SKU_AMOUNT in", values, "skuAmount");
            return (Criteria) this;
        }

        public Criteria andSkuAmountNotIn(List<BigDecimal> values) {
            addCriterion("SKU_AMOUNT not in", values, "skuAmount");
            return (Criteria) this;
        }

        public Criteria andSkuAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SKU_AMOUNT between", value1, value2, "skuAmount");
            return (Criteria) this;
        }

        public Criteria andSkuAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SKU_AMOUNT not between", value1, value2, "skuAmount");
            return (Criteria) this;
        }

        public Criteria andIsSevenIsNull() {
            addCriterion("IS_SEVEN is null");
            return (Criteria) this;
        }

        public Criteria andIsSevenIsNotNull() {
            addCriterion("IS_SEVEN is not null");
            return (Criteria) this;
        }

        public Criteria andIsSevenEqualTo(Integer value) {
            addCriterion("IS_SEVEN =", value, "isSeven");
            return (Criteria) this;
        }

        public Criteria andIsSevenNotEqualTo(Integer value) {
            addCriterion("IS_SEVEN <>", value, "isSeven");
            return (Criteria) this;
        }

        public Criteria andIsSevenGreaterThan(Integer value) {
            addCriterion("IS_SEVEN >", value, "isSeven");
            return (Criteria) this;
        }

        public Criteria andIsSevenGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_SEVEN >=", value, "isSeven");
            return (Criteria) this;
        }

        public Criteria andIsSevenLessThan(Integer value) {
            addCriterion("IS_SEVEN <", value, "isSeven");
            return (Criteria) this;
        }

        public Criteria andIsSevenLessThanOrEqualTo(Integer value) {
            addCriterion("IS_SEVEN <=", value, "isSeven");
            return (Criteria) this;
        }

        public Criteria andIsSevenIn(List<Integer> values) {
            addCriterion("IS_SEVEN in", values, "isSeven");
            return (Criteria) this;
        }

        public Criteria andIsSevenNotIn(List<Integer> values) {
            addCriterion("IS_SEVEN not in", values, "isSeven");
            return (Criteria) this;
        }

        public Criteria andIsSevenBetween(Integer value1, Integer value2) {
            addCriterion("IS_SEVEN between", value1, value2, "isSeven");
            return (Criteria) this;
        }

        public Criteria andIsSevenNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_SEVEN not between", value1, value2, "isSeven");
            return (Criteria) this;
        }

        public Criteria andSevenIsNull() {
            addCriterion("SEVEN is null");
            return (Criteria) this;
        }

        public Criteria andSevenIsNotNull() {
            addCriterion("SEVEN is not null");
            return (Criteria) this;
        }

        public Criteria andSevenEqualTo(String value) {
            addCriterion("SEVEN =", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenNotEqualTo(String value) {
            addCriterion("SEVEN <>", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenGreaterThan(String value) {
            addCriterion("SEVEN >", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenGreaterThanOrEqualTo(String value) {
            addCriterion("SEVEN >=", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenLessThan(String value) {
            addCriterion("SEVEN <", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenLessThanOrEqualTo(String value) {
            addCriterion("SEVEN <=", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenLike(String value) {
            addCriterion("SEVEN like", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenNotLike(String value) {
            addCriterion("SEVEN not like", value, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenIn(List<String> values) {
            addCriterion("SEVEN in", values, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenNotIn(List<String> values) {
            addCriterion("SEVEN not in", values, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenBetween(String value1, String value2) {
            addCriterion("SEVEN between", value1, value2, "seven");
            return (Criteria) this;
        }

        public Criteria andSevenNotBetween(String value1, String value2) {
            addCriterion("SEVEN not between", value1, value2, "seven");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}