package com.vedeng.mjx.mapper;

import com.vedeng.mjx.domain.TAttachment;
import com.vedeng.mjx.domain.TAttachmentExample;
import com.vedeng.mjx.domain.TAttachmentKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated
     */
    long countByExample(TAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated
     */
    int deleteByExample(TAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TAttachmentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated
     */
    int insert(TAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated
     */
    int insertSelective(TAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated
     */
    List<TAttachment> selectByExample(TAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated
     */
    TAttachment selectByPrimaryKey(TAttachmentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TAttachment record, @Param("example") TAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TAttachment record, @Param("example") TAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TAttachment record);
}