package com.vedeng.mjx.mapper;

import com.vedeng.mjx.domain.TBrandJx;
import com.vedeng.mjx.domain.TBrandJxExample;
import com.vedeng.mjx.domain.TBrandJxKey;
import com.vedeng.mjx.domain.TBrandJxWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBrandJxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND_JX
     *
     * @mbg.generated
     */
    long countByExample(TBrandJxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND_JX
     *
     * @mbg.generated
     */
    int deleteByExample(TBrandJxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND_JX
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TBrandJxKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND_JX
     *
     * @mbg.generated
     */
    int insert(TBrandJxWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND_JX
     *
     * @mbg.generated
     */
    int insertSelective(TBrandJxWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND_JX
     *
     * @mbg.generated
     */
    List<TBrandJxWithBLOBs> selectByExampleWithBLOBs(TBrandJxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND_JX
     *
     * @mbg.generated
     */
    List<TBrandJx> selectByExample(TBrandJxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND_JX
     *
     * @mbg.generated
     */
    TBrandJxWithBLOBs selectByPrimaryKey(TBrandJxKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND_JX
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TBrandJxWithBLOBs record, @Param("example") TBrandJxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND_JX
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TBrandJxWithBLOBs record, @Param("example") TBrandJxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND_JX
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TBrandJx record, @Param("example") TBrandJxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND_JX
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TBrandJxWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND_JX
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TBrandJxWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND_JX
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBrandJx record);
}