package com.vedeng.mjx.mapper;

import com.vedeng.mjx.domain.*;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND
     *
     * @mbg.generated
     */
    long countByExample(TBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND
     *
     * @mbg.generated
     */
    int deleteByExample(TBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TBrandKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND
     *
     * @mbg.generated
     */
    int insert(TBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND
     *
     * @mbg.generated
     */
    int insertSelective(TBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND
     *
     * @mbg.generated
     */
    List<TBrandWithBLOBs> selectByExampleWithBLOBs(TBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND
     *
     * @mbg.generated
     */
    List<TBrand> selectByExample(TBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND
     *
     * @mbg.generated
     */
    TBrandWithBLOBs selectByPrimaryKey(TBrandKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TBrandWithBLOBs record, @Param("example") TBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TBrandWithBLOBs record, @Param("example") TBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TBrand record, @Param("example") TBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BRAND
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBrand record);

    List<TBrand> selectBrandbyEntity(TBrand tBrand);

    List<TBrandData> selectBrandList(List<String> list);


    List<TBrand> getAllBrand();

}