package com.vedeng.mjx.mapper;

import com.vedeng.mjx.domain.TCategoryJx;
import com.vedeng.mjx.domain.TCategoryJxExample;
import com.vedeng.mjx.domain.TCategoryJxKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCategoryJxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CATEGORY_JX
     *
     * @mbg.generated
     */
    long countByExample(TCategoryJxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CATEGORY_JX
     *
     * @mbg.generated
     */
    int deleteByExample(TCategoryJxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CATEGORY_JX
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TCategoryJxKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CATEGORY_JX
     *
     * @mbg.generated
     */
    int insert(TCategoryJx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CATEGORY_JX
     *
     * @mbg.generated
     */
    int insertSelective(TCategoryJx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CATEGORY_JX
     *
     * @mbg.generated
     */
    List<TCategoryJx> selectByExample(TCategoryJxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CATEGORY_JX
     *
     * @mbg.generated
     */
    TCategoryJx selectByPrimaryKey(TCategoryJxKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CATEGORY_JX
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCategoryJx record, @Param("example") TCategoryJxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CATEGORY_JX
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCategoryJx record, @Param("example") TCategoryJxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CATEGORY_JX
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCategoryJx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CATEGORY_JX
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCategoryJx record);
}