package com.vedeng.mjx.mapper;

import com.vedeng.mjx.domain.TDepartmentsHospital;
import com.vedeng.mjx.domain.TDepartmentsHospitalExample;
import com.vedeng.mjx.domain.TDepartmentsHospitalKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TDepartmentsHospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPARTMENTS_HOSPITAL
     *
     * @mbg.generated
     */
    long countByExample(TDepartmentsHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPARTMENTS_HOSPITAL
     *
     * @mbg.generated
     */
    int deleteByExample(TDepartmentsHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPARTMENTS_HOSPITAL
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TDepartmentsHospitalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPARTMENTS_HOSPITAL
     *
     * @mbg.generated
     */
    int insert(TDepartmentsHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPARTMENTS_HOSPITAL
     *
     * @mbg.generated
     */
    int insertSelective(TDepartmentsHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPARTMENTS_HOSPITAL
     *
     * @mbg.generated
     */
    List<TDepartmentsHospital> selectByExample(TDepartmentsHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPARTMENTS_HOSPITAL
     *
     * @mbg.generated
     */
    TDepartmentsHospital selectByPrimaryKey(TDepartmentsHospitalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPARTMENTS_HOSPITAL
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TDepartmentsHospital record, @Param("example") TDepartmentsHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPARTMENTS_HOSPITAL
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TDepartmentsHospital record, @Param("example") TDepartmentsHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPARTMENTS_HOSPITAL
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDepartmentsHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPARTMENTS_HOSPITAL
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDepartmentsHospital record);

    List<TDepartmentsHospital> selectDepartmentsHospitalbyEntity(TDepartmentsHospital tDepartmentsHospital);
}