package com.vedeng.mjx.mapper;

import com.vedeng.mjx.domain.TOpAccountAddress;
import com.vedeng.mjx.domain.TOpAccountAddressExample;
import com.vedeng.mjx.domain.TOpAccountAddressKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TOpAccountAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_ACCOUNT_ADDRESS
     *
     * @mbg.generated
     */
    long countByExample(TOpAccountAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_ACCOUNT_ADDRESS
     *
     * @mbg.generated
     */
    int deleteByExample(TOpAccountAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_ACCOUNT_ADDRESS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TOpAccountAddressKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_ACCOUNT_ADDRESS
     *
     * @mbg.generated
     */
    int insert(TOpAccountAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_ACCOUNT_ADDRESS
     *
     * @mbg.generated
     */
    int insertSelective(TOpAccountAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_ACCOUNT_ADDRESS
     *
     * @mbg.generated
     */
    List<TOpAccountAddress> selectByExample(TOpAccountAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_ACCOUNT_ADDRESS
     *
     * @mbg.generated
     */
    TOpAccountAddress selectByPrimaryKey(TOpAccountAddressKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_ACCOUNT_ADDRESS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TOpAccountAddress record, @Param("example") TOpAccountAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_ACCOUNT_ADDRESS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TOpAccountAddress record, @Param("example") TOpAccountAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_ACCOUNT_ADDRESS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TOpAccountAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_ACCOUNT_ADDRESS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TOpAccountAddress record);
}