package com.vedeng.mjx.mapper;

import com.vedeng.mjx.domain.TOpSku;
import com.vedeng.mjx.domain.TOpSkuExample;
import com.vedeng.mjx.domain.TOpSkuKey;
import com.vedeng.mjx.domain.TOpSkuWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TOpSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_SKU
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    long countByExample(TOpSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_SKU
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    int deleteByExample(TOpSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_SKU
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    int deleteByPrimaryKey(TOpSkuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_SKU
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    int insert(TOpSkuWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_SKU
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    int insertSelective(TOpSkuWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_SKU
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    List<TOpSkuWithBLOBs> selectByExampleWithBLOBs(TOpSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_SKU
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    List<TOpSku> selectByExample(TOpSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_SKU
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    TOpSkuWithBLOBs selectByPrimaryKey(TOpSkuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_SKU
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") TOpSkuWithBLOBs record, @Param("example") TOpSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_SKU
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") TOpSkuWithBLOBs record, @Param("example") TOpSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_SKU
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    int updateByExample(@Param("record") TOpSku record, @Param("example") TOpSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_SKU
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    int updateByPrimaryKeySelective(TOpSkuWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_SKU
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TOpSkuWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OP_SKU
     *
     * @mbg.generated Mon Jul 15 11:13:17 CST 2019
     */
    int updateByPrimaryKey(TOpSku record);
}