package com.vedeng.mjx.mapper;

import com.vedeng.mjx.domain.*;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_BRAND
     *
     * @mbg.generated
     */
    long countByExample(VBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_BRAND
     *
     * @mbg.generated
     */
    int deleteByExample(VBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_BRAND
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(VBrandKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_BRAND
     *
     * @mbg.generated
     */
    int insert(VBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_BRAND
     *
     * @mbg.generated
     */
    int insertSelective(VBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_BRAND
     *
     * @mbg.generated
     */
    List<VBrandWithBLOBs> selectByExampleWithBLOBs(VBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_BRAND
     *
     * @mbg.generated
     */
    List<VBrand> selectByExample(VBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_BRAND
     *
     * @mbg.generated
     */
    VBrandWithBLOBs selectByPrimaryKey(VBrandKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_BRAND
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VBrandWithBLOBs record, @Param("example") VBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_BRAND
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") VBrandWithBLOBs record, @Param("example") VBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_BRAND
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VBrand record, @Param("example") VBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_BRAND
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_BRAND
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(VBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_BRAND
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VBrand record);

    List<TBrandData> selectBrandList(List<String> list);

}