package com.vedeng.mjx.mapper;

import com.vedeng.mjx.domain.VGoodsCar;
import com.vedeng.mjx.domain.VGoodsCarExample;
import com.vedeng.mjx.domain.VGoodsCarKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VGoodsCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_GOODS_CAR
     *
     * @mbg.generated
     */
    long countByExample(VGoodsCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_GOODS_CAR
     *
     * @mbg.generated
     */
    int deleteByExample(VGoodsCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_GOODS_CAR
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(VGoodsCarKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_GOODS_CAR
     *
     * @mbg.generated
     */
    int insert(VGoodsCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_GOODS_CAR
     *
     * @mbg.generated
     */
    int insertSelective(VGoodsCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_GOODS_CAR
     *
     * @mbg.generated
     */
    List<VGoodsCar> selectByExample(VGoodsCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_GOODS_CAR
     *
     * @mbg.generated
     */
    VGoodsCar selectByPrimaryKey(VGoodsCarKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_GOODS_CAR
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VGoodsCar record, @Param("example") VGoodsCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_GOODS_CAR
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VGoodsCar record, @Param("example") VGoodsCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_GOODS_CAR
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VGoodsCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_GOODS_CAR
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VGoodsCar record);
}