package com.vedeng.mjx.mapper;

import com.vedeng.mjx.domain.VOrderGoods;
import com.vedeng.mjx.domain.VOrderGoodsExample;
import com.vedeng.mjx.domain.VOrderGoodsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface VOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    long countByExample(VOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    int deleteByExample(VOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(VOrderGoodsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    int insert(VOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    int insertSelective(VOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    List<VOrderGoods> selectByExample(VOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    VOrderGoods selectByPrimaryKey(VOrderGoodsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VOrderGoods record, @Param("example") VOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VOrderGoods record, @Param("example") VOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER_GOODS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VOrderGoods record);

    VOrderGoods selectOneUrlByOrderNo(String orderNo);

}