package com.vedeng.mjx.mapper;

import com.vedeng.mjx.domain.OrderCountData;
import com.vedeng.mjx.domain.VOrder;
import com.vedeng.mjx.domain.VOrderExample;
import com.vedeng.mjx.domain.VOrderKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER
     *
     * @mbg.generated
     */
    long countByExample(VOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER
     *
     * @mbg.generated
     */
    int deleteByExample(VOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(VOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER
     *
     * @mbg.generated
     */
    int insert(VOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER
     *
     * @mbg.generated
     */
    int insertSelective(VOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER
     *
     * @mbg.generated
     */
    List<VOrder> selectByExample(VOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER
     *
     * @mbg.generated
     */
    VOrder selectByPrimaryKey(VOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VOrder record, @Param("example") VOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VOrder record, @Param("example") VOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ORDER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VOrder record);

    List<OrderCountData> selectCountByOrderStstus(Integer accountId);

    List<VOrder> orderList(@Param("accountId") Integer accountId,@Param("list") List<Integer> list);

}