package com.vedeng.mjx.mapper;

import com.vedeng.mjx.domain.VSku;
import com.vedeng.mjx.domain.VSkuExample;
import com.vedeng.mjx.domain.VSkuKey;
import com.vedeng.mjx.domain.VSkuWithBLOBs;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface VSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SKU
     *
     * @mbg.generated
     */
    long countByExample(VSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SKU
     *
     * @mbg.generated
     */
    int deleteByExample(VSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SKU
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(VSkuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SKU
     *
     * @mbg.generated
     */
    int insert(VSkuWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SKU
     *
     * @mbg.generated
     */
    int insertSelective(VSkuWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SKU
     *
     * @mbg.generated
     */
    List<VSkuWithBLOBs> selectByExampleWithBLOBs(VSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SKU
     *
     * @mbg.generated
     */
    List<VSku> selectByExample(VSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SKU
     *
     * @mbg.generated
     */
    VSkuWithBLOBs selectByPrimaryKey(VSkuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SKU
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VSkuWithBLOBs record, @Param("example") VSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SKU
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") VSkuWithBLOBs record, @Param("example") VSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SKU
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VSku record, @Param("example") VSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SKU
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VSkuWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SKU
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(VSkuWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_SKU
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VSku record);
}