package com.vedeng.mjx.mapper;

import com.vedeng.mjx.domain.VVersion;
import com.vedeng.mjx.domain.VVersionExample;
import com.vedeng.mjx.domain.VVersionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_VERSION
     *
     * @mbg.generated
     */
    long countByExample(VVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_VERSION
     *
     * @mbg.generated
     */
    int deleteByExample(VVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_VERSION
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(VVersionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_VERSION
     *
     * @mbg.generated
     */
    int insert(VVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_VERSION
     *
     * @mbg.generated
     */
    int insertSelective(VVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_VERSION
     *
     * @mbg.generated
     */
    List<VVersion> selectByExample(VVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_VERSION
     *
     * @mbg.generated
     */
    VVersion selectByPrimaryKey(VVersionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_VERSION
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VVersion record, @Param("example") VVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_VERSION
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VVersion record, @Param("example") VVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_VERSION
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_VERSION
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VVersion record);

    VVersion selectVersionNew(@Param("client") Integer client,@Param("platformId") Integer platformId);

}