package com.vedeng.mjx.mapper;

import com.vedeng.mjx.domain.VWxPhone;
import com.vedeng.mjx.domain.VWxPhoneExample;
import com.vedeng.mjx.domain.VWxPhoneKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VWxPhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_WX_PHONE
     *
     * @mbg.generated
     */
    long countByExample(VWxPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_WX_PHONE
     *
     * @mbg.generated
     */
    int deleteByExample(VWxPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_WX_PHONE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(VWxPhoneKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_WX_PHONE
     *
     * @mbg.generated
     */
    int insert(VWxPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_WX_PHONE
     *
     * @mbg.generated
     */
    int insertSelective(VWxPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_WX_PHONE
     *
     * @mbg.generated
     */
    List<VWxPhone> selectByExample(VWxPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_WX_PHONE
     *
     * @mbg.generated
     */
    VWxPhone selectByPrimaryKey(VWxPhoneKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_WX_PHONE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VWxPhone record, @Param("example") VWxPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_WX_PHONE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VWxPhone record, @Param("example") VWxPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_WX_PHONE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VWxPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_WX_PHONE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VWxPhone record);
}